"""Auto-titling: a titleless conversation gets a short name from its first
successful turn, generated by a cheap, non-blocking side call - not the
agent loop `query()` runs. See app/agent.py's _maybe_title_conversation and
docs in CLAUDE.md's Phase-5 backlog note.
"""

from __future__ import annotations

import asyncio
import json
from typing import TYPE_CHECKING, cast
from unittest.mock import AsyncMock, MagicMock

import pytest
from anthropic.types import TextBlock as AnthropicTextBlock

from app import agent
from app.conversations import ConversationRegistry

if TYPE_CHECKING:
    from app.session_store import PostgresSessionStore


def run(coro):
    return asyncio.run(coro)


def attach(registry: ConversationRegistry, store: object) -> None:
    """The fakes below only need get_conversation/set_conversation_title_if_unset,
    but attach_store's parameter is the concrete PostgresSessionStore rather
    than a Protocol - unlike signals.TurnOutcomeStore, which was split out
    specifically so a test double type-checks. Not worth doing the same split
    here for one test file, so this cast is the narrow workaround."""
    registry.attach_store(cast("PostgresSessionStore", store))


def _text_response(text: str):
    block = MagicMock(spec=AnthropicTextBlock)
    block.text = text
    response = MagicMock()
    response.content = [block]
    return response


class _FakeStore:
    def __init__(self, *, conversation: dict | None):
        self.conversation = conversation
        self.set_calls: list[tuple[str, str]] = []
        self.set_result = True

    async def get_conversation(self, conversation_id: str) -> dict | None:
        return self.conversation

    async def set_conversation_title_if_unset(
        self, conversation_id: str, title: str
    ) -> bool:
        self.set_calls.append((conversation_id, title))
        return self.set_result


# -- ConversationRegistry.needs_title / set_title_if_unset ------------------


def test_needs_title_true_when_conversation_has_no_title():
    registry = ConversationRegistry()
    attach(registry, _FakeStore(conversation={"id": "c1", "title": None}))

    assert run(registry.needs_title("c1")) is True


def test_needs_title_false_when_title_already_set():
    registry = ConversationRegistry()
    attach(registry, _FakeStore(conversation={"id": "c1", "title": "Existing"}))

    assert run(registry.needs_title("c1")) is False


def test_needs_title_false_with_no_store():
    registry = ConversationRegistry()

    assert run(registry.needs_title("c1")) is False


def test_needs_title_false_when_conversation_missing():
    registry = ConversationRegistry()
    attach(registry, _FakeStore(conversation=None))

    assert run(registry.needs_title("c1")) is False


def test_needs_title_false_on_store_exception():
    class _Broken(_FakeStore):
        async def get_conversation(self, conversation_id: str) -> dict | None:
            raise RuntimeError("db is down")

    registry = ConversationRegistry()
    attach(registry, _Broken(conversation=None))

    assert run(registry.needs_title("c1")) is False


def test_set_title_if_unset_delegates_and_returns_result():
    store = _FakeStore(conversation=None)
    store.set_result = True
    registry = ConversationRegistry()
    attach(registry, store)

    assert run(registry.set_title_if_unset("c1", "A Title")) is True
    assert store.set_calls == [("c1", "A Title")]


def test_set_title_if_unset_false_on_store_exception():
    class _Broken(_FakeStore):
        async def set_conversation_title_if_unset(
            self, conversation_id: str, title: str
        ) -> bool:
            raise RuntimeError("db is down")

    registry = ConversationRegistry()
    attach(registry, _Broken(conversation=None))

    assert run(registry.set_title_if_unset("c1", "A Title")) is False


# -- agent._maybe_title_conversation -----------------------------------------


@pytest.fixture
def mock_conversations(monkeypatch):
    mock = MagicMock()
    mock.needs_title = AsyncMock(return_value=True)
    mock.set_title_if_unset = AsyncMock(return_value=True)
    mock.flush_one = AsyncMock()
    mock.get = MagicMock(return_value=MagicMock())
    monkeypatch.setattr(agent, "conversations", mock)
    return mock


@pytest.fixture
def mock_anthropic(monkeypatch):
    client = MagicMock()
    client.messages.create = AsyncMock(return_value=_text_response("A Great Title"))
    monkeypatch.setattr(agent, "AsyncAnthropic", MagicMock(return_value=client))
    return client


def test_blank_prompt_never_calls_needs_title(mock_conversations, mock_anthropic):
    run(agent._maybe_title_conversation("c1", "   "))

    mock_conversations.needs_title.assert_not_called()
    mock_anthropic.messages.create.assert_not_called()


def test_title_already_set_skips_the_model_call(mock_conversations, mock_anthropic):
    mock_conversations.needs_title.return_value = False

    run(agent._maybe_title_conversation("c1", "hello there"))

    mock_anthropic.messages.create.assert_not_called()
    mock_conversations.set_title_if_unset.assert_not_called()


def test_model_failure_is_swallowed(mock_conversations, mock_anthropic):
    mock_anthropic.messages.create.side_effect = RuntimeError("boom")

    run(agent._maybe_title_conversation("c1", "hello there"))

    mock_conversations.set_title_if_unset.assert_not_called()


def test_happy_path_sets_title_and_pushes_a_live_event(
    mock_conversations, mock_anthropic
):
    mock_anthropic.messages.create.return_value = _text_response('  "A Great Title"  ')

    run(agent._maybe_title_conversation("c1", "hello there"))

    mock_conversations.set_title_if_unset.assert_awaited_once_with(
        "c1", "A Great Title"
    )
    conv = mock_conversations.get.return_value
    conv.append.assert_called_once()
    kind, data = conv.append.call_args.args
    assert kind == "title"
    assert json.loads(data) == {"title": "A Great Title"}
    mock_conversations.flush_one.assert_awaited_once_with("c1")


def test_losing_the_race_does_not_push_a_live_event(mock_conversations, mock_anthropic):
    mock_conversations.set_title_if_unset.return_value = False

    run(agent._maybe_title_conversation("c1", "hello there"))

    mock_conversations.get.assert_not_called()
    mock_conversations.flush_one.assert_not_awaited()


def test_title_is_truncated_to_the_max_length(mock_conversations, mock_anthropic):
    long_text = "x" * (agent._TITLE_MAX_CHARS + 40)
    mock_anthropic.messages.create.return_value = _text_response(long_text)

    run(agent._maybe_title_conversation("c1", "hello there"))

    (_, title), _kwargs = mock_conversations.set_title_if_unset.call_args
    assert len(title) == agent._TITLE_MAX_CHARS
