"""The commit-hook installer, which has to share a file it does not own.

`scripts/install-hooks.sh` writes into whatever directory `core.hooksPath` names,
because `bd` points that at `.beads/hooks` and git then ignores `.git/hooks`
entirely. Sharing is the whole design, so the property to hold is negative: text
this script did not write must still be there afterwards. Get that wrong and
beads' own hooks stop running with no error anywhere - which is the failure mode
`img-bl4` was filed about, arriving from the other side.

No test here runs the gate itself. That needs uvx, a network on first use and a
populated `.venv`, which is the container tier's business rather than this one's.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
INSTALLER = REPO / "scripts" / "install-hooks.sh"
CHECKS = REPO / "scripts" / "pre-commit-checks.sh"

FOREIGN = (
    "# --- BEGIN BEADS INTEGRATION v1.2.1 ---\n"
    "echo beads ran\n"
    "# --- END BEADS INTEGRATION v1.2.1 ---\n"
)


def _git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A git repo carrying the installer, with hooks redirected as bd leaves them."""
    work = tmp_path / "repo"
    (work / "scripts").mkdir(parents=True)
    for script in (INSTALLER, CHECKS):
        target = work / "scripts" / script.name
        target.write_text(script.read_text())
        target.chmod(0o755)
    _git(work, "init", "-q", ".")
    hooks = work / ".beads" / "hooks"
    hooks.mkdir(parents=True)
    _git(work, "config", "core.hooksPath", str(hooks))
    return work


def _install(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(repo / "scripts" / "install-hooks.sh")],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )


def _hook(repo: Path) -> Path:
    return repo / ".beads" / "hooks" / "pre-commit"


def test_it_writes_where_core_hookspath_points(repo: Path) -> None:
    # The whole bug was a hook installed somewhere git does not look, so this
    # asserts the location and not merely that some file appeared.
    assert _install(repo).returncode == 0
    assert _hook(repo).exists(), ".git/hooks would be ignored; the hook must land here"
    assert not (repo / ".git" / "hooks" / "pre-commit").exists()
    assert os.access(_hook(repo), os.X_OK), "git silently skips a non-executable hook"


def test_it_calls_the_script_rather_than_inlining_the_gate(repo: Path) -> None:
    # The block is generated by the installer, so inlining the checks there would
    # put them beyond ruff, ty and this suite, and changing them would mean every
    # checkout re-running the installer. Delegating is the load-bearing part.
    #
    # Asserted by running it against a stub rather than by finding the path in the
    # file: a mutation that inlined the gate and left the surrounding comment
    # mentioning the script passed the textual version of this test.
    _install(repo)
    stub = repo / "scripts" / "pre-commit-checks.sh"
    stub.write_text("#!/usr/bin/env sh\ntouch ran.marker\nexit 1\n")
    stub.chmod(0o755)
    done = subprocess.run(
        ["sh", str(_hook(repo))],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )
    assert (repo / "ran.marker").exists(), "the hook never reached the script"
    assert done.returncode != 0, "the script failed but the hook let the commit through"


def test_running_it_twice_leaves_one_copy(repo: Path) -> None:
    _install(repo)
    _install(repo)
    body = _hook(repo).read_text()
    assert body.count("BEGIN MEMORY-AGENT STATIC CHECKS") == 1
    assert body.count("END MEMORY-AGENT STATIC CHECKS") == 1


def test_it_preserves_a_block_it_did_not_write(repo: Path) -> None:
    # Stands in for `bd hooks install`: beads owns a marked region of this same
    # file, and losing it disables its hooks with no error anywhere.
    _hook(repo).write_text("#!/usr/bin/env sh\n" + FOREIGN)
    _install(repo)
    body = _hook(repo).read_text()
    assert FOREIGN in body, "the beads block was clobbered"
    assert body.startswith("#!/usr/bin/env sh\n"), "the shebang must stay first"
    assert "BEGIN MEMORY-AGENT STATIC CHECKS" in body


def test_reinstalling_over_our_own_block_keeps_a_foreign_one(repo: Path) -> None:
    # The stripping pass is regex-free line matching on our markers; this catches
    # it widening to swallow whatever follows.
    _install(repo)
    with _hook(repo).open("a") as fh:
        fh.write(FOREIGN)
    _install(repo)
    body = _hook(repo).read_text()
    assert FOREIGN in body
    assert body.count("BEGIN MEMORY-AGENT STATIC CHECKS") == 1


def test_the_hook_survives_the_script_being_absent(repo: Path) -> None:
    # Checking out a commit older than the script must not fail every commit
    # after it, so the hook guards on -x rather than calling blind.
    _install(repo)
    (repo / "scripts" / "pre-commit-checks.sh").unlink()
    done = subprocess.run(
        ["sh", str(_hook(repo))],
        cwd=repo,
        check=False,
        capture_output=True,
        text=True,
    )
    assert done.returncode == 0, done.stderr
